### ISSUE TITLE
Implement performance metrics 

### ISSUE THREAD

**Issue by p16i** [heytitle/thai-tokenisers#1]
Based on this discussion from https://github.com/heytitle/thai-word-tokenisation-benchmark/issues/8. 

It would be good if we also benchmark performance of each tokeniser on other aspects. These aspects include:

## Speed

Characters per second (on standardized machine)
May be tested with different sizes of text (small and large), to notice the "boot time" of a tokenizer

## Memory footprint

Memory used by the tokenizer (when tokenizing a certain amount of text), at the running time

## Disk size

Total size of the tokenizer, including dictionary, models, and all non-standard dependencies (excluding runtime environment, like interpreter/VM)

**Comment by p16i** [comment]
Before implementing these metrics, I think we need to consider the followings:
1. Use the same base Docker image for all methods. 
2. Not use GPU version of any deep learning framework. 

## Thoughts on the implementations
### Speed
- Characters per second is quite straightforward to implement. However, I'm not sure about the definition of "boot time". 

### Memory Footprint
- We might use [`memory-profiler`](https://pypi.org/project/memory-profiler).

### Disk Size
- Because we're going to use the same base Docker image. We might compute the disk size used by each method by the difference of a reference image and the final image, i.e. the images before and after installing the package.

**Comment by bact** [comment]
> Characters per second is quite straightforward to implement. However, I'm not sure about the definition of "boot time". 

"Boot time" is time from the cold start of the program until it is ready for actual work. In the context of tokenizer, this can be dictionary loading time or language model loading time, something that will will only do once.

## Example
Let
- Tokenizer A: Boot time is 30 secs. After than can tokenize text at 500 chars/sec.
- Tokenizer B: Boot time is 5 secs. After than can tokenize text at 20 chars/sec.

If text is 20 characters:
- A: 30 + 0.04 ~= 31 secs
- B: 5 + 1 = 6 secs

If text is 2,000 characters:
- A: 30 + 4 = 34 secs
- B: 5 + 100 = 105 secs

## Different use cases

This will depends on use can as well.

If the entire tokenizer is loaded only once, the boot time can be ignored. As in the long run it will be irrelevant.

In some other cases, as may occurs in scripting environment, that the tokenizer will be loaded everytime it got call, boot time can be significant.

**Comment by p16i** [comment]
Hi @bact,

I've made a Jupyter notebook on Colab to test the speed of each tokeniser.  I think this Colab solution is good for this purpose because the machine is standardised and easily to be reproduced. 

Please see the results below:
![Unknown-2](https://user-images.githubusercontent.com/1214890/58615566-97f44300-82e5-11e9-85c0-329729db5da4.png)

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1214890/58615533-84e17300-82e5-11e9-8820-80bc647e2ff9.png">

[Link to Colab][link]

[link]: https://colab.research.google.com/drive/1SuNYLiwEkOln_WGP_BekumGP4CxRm9rp
